import { ArrowLeft, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Section = ({ title, children }) => (
  <section style={{ marginBottom: '1.2rem' }}>
    <h2 style={{ fontSize: '0.92rem', margin: '0 0 0.45rem', color: '#ffffff', fontWeight: 850 }}>{title}</h2>
    <p style={{ margin: 0, color: '#a8b3c7', fontSize: '0.78rem', lineHeight: 1.65 }}>{children}</p>
  </section>
);

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div style={{ minHeight: '100vh', width: '100%', background: 'var(--bg-color)', color: '#ffffff', overflowY: 'auto', padding: '22px 18px 36px', boxSizing: 'border-box' }}>
      <div style={{ width: '100%', maxWidth: '520px', margin: '0 auto' }}>
        <button
          onClick={() => navigate(-1)}
          style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', color: '#cbd5e1', borderRadius: '999px', padding: '8px 12px', fontSize: '0.78rem', fontWeight: 800, cursor: 'pointer', marginBottom: '18px' }}
        >
          <ArrowLeft size={15} /> Back
        </button>

        <div className="glass-panel" style={{ padding: '22px', borderRadius: '18px' }}>
          <div style={{ width: '48px', height: '48px', borderRadius: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(96,165,250,0.12)', border: '1px solid rgba(96,165,250,0.28)', marginBottom: '14px' }}>
            <FileText size={24} color="#60a5fa" />
          </div>
          <h1 style={{ fontSize: '1.55rem', margin: '0 0 0.35rem', fontWeight: 950 }}>Terms of Use</h1>
          <p style={{ margin: '0 0 1.4rem', color: '#94a3b8', fontSize: '0.76rem' }}>Effective July 4, 2026</p>

          <Section title="Learning app">
            Memeng is a vocabulary learning tool. It helps you translate, save, and review words, but it cannot guarantee perfect memory or perfect translations.
          </Section>

          <Section title="AI content">
            Some explanations, examples, images, and translations may be generated by AI or third-party services. They can be wrong, so use your own judgment before relying on them.
          </Section>

          <Section title="Your account">
            You are responsible for the activity on your account and for keeping your login safe. Do not use the app to abuse services, bypass limits, or upload harmful content.
          </Section>

          <Section title="Limits and availability">
            Free limits, AI access, features, and hosting can change over time. The app may be unavailable during maintenance, provider outages, or quota limits.
          </Section>

          <Section title="Changes">
            These terms may be updated as the product grows. Continuing to use the app after changes means you accept the updated terms.
          </Section>
        </div>
      </div>
    </div>
  );
};

export default Terms;