import fs from 'fs';
import path from 'path';
import fetch from 'node-fetch';

/**
 * VocabSync Automated Sourcing Pipeline
 * ------------------------------------
 * Reads the GIPHY_API_KEY from .env.local
 * Fetches Dictionary Data + GIPHY MP4s
 * Outputs a ready-to-run SQL file to bypass RLS securely!
 */

// Read .env.local manually since we don't have dotenv
const envPath = path.join(process.cwd(), '.env.local');
let envFile = '';
try {
  envFile = fs.readFileSync(envPath, 'utf-8');
} catch (e) {
  console.log("Could not find .env.local");
}
const giphyMatch = envFile.match(/GIPHY_API_KEY=(.*)/);
const GIPHY_API_KEY = giphyMatch ? giphyMatch[1].trim() : 'YOUR_GIPHY_KEY_HERE';

// 50 Hand-picked Oxford 5000 Words
// Note: Limited to 50 because the free GIPHY Beta Key allows strictly 100 calls/hour.
const oxfordWords = [
  "Abundant", "Accommodate", "Accumulate", "Adapt", "Adequate",
  "Advocate", "Allocate", "Ambiguous", "Amend", "Analyze",
  "Appreciate", "Arbitrary", "Assess", "Attain", "Attitude",
  "Attribute", "Automate", "Aware", "Benefit", "Bias",
  "Brief", "Capable", "Capacity", "Cease", "Clarify",
  "Coherent", "Coincide", "Collaborate", "Collapse", "Compile",
  "Complex", "Conceive", "Conclude", "Concurrent", "Conduct",
  "Confer", "Confine", "Confirm", "Conflict", "Conform",
  "Consent", "Consequence", "Considerable", "Consist", "Constant",
  "Constitutional", "Constraint", "Construct", "Consult", "Consume"
];

const fetchWordData = async (word) => {
  try {
    // 1. Get Dictionary Data
    let dictRes = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`);
    if (!dictRes.ok) throw new Error("Not found in Dictionary");
    let dictJson = await dictRes.json();
    
    const rawData = dictJson[0].meanings[0];
    const pos = rawData.partOfSpeech;
    const meaning = rawData.definitions[0].definition;
    const example = rawData.definitions[0].example || `This is an example sentence for ${word}.`;

    // Extract pre/post string
    const lowerSentence = example.toLowerCase();
    const lowerWord = word.toLowerCase();
    const index = lowerSentence.indexOf(lowerWord);
    
    let pre = example;
    let post = '';
    if (index !== -1) {
       pre = example.substring(0, index);
       post = example.substring(index + word.length);
    }

    // 2. Get GIPHY Video
    let videoUrl = '';
    let giphyRes = await fetch(`https://api.giphy.com/v1/gifs/search?api_key=${GIPHY_API_KEY}&q=${word}&limit=1&rating=g`);
    if (giphyRes.ok) {
        let giphyJson = await giphyRes.json();
        if (giphyJson.data && giphyJson.data.length > 0) {
            videoUrl = giphyJson.data[0].images.original.mp4;
        }
    }

    // Return SQL Values String
    // We escape single quotes using '' for SQL
    const escapeSql = (str) => str ? str.replace(/'/g, "''") : '';
    
    return `('${escapeSql(word)}', '${escapeSql(pos)}', '${escapeSql(meaning)}', '${escapeSql(pre)}', '${escapeSql(post)}', ${videoUrl ? `'${videoUrl}'` : 'NULL'}, 'Intermediate')`;

  } catch (err) {
    console.log(`❌ Skipped "${word}": ${err.message}`);
    return null;
  }
};

const runPipeline = async () => {
  console.log("🚀 Starting VocabSync Automated Pipeline...");
  console.log(`Using Giphy Key starting with: ${GIPHY_API_KEY.substring(0, 5)}...`);
  
  let sqlStatements = `
-- VocabSync Global Dictionary Seed File
-- Auto-generated by seedAutomation.js

INSERT INTO public.global_dictionary (word, pos, meaning, sentence_pre, sentence_post, video_url, cefr_level)
VALUES
`;

  const values = [];
  let count = 0;

  for (const word of oxfordWords) {
    count++;
    console.log(`[${count}/${oxfordWords.length}] Processing: ${word}...`);
    const sqlValue = await fetchWordData(word);
    if (sqlValue) {
      values.push(sqlValue);
      console.log(`✅ Success`);
    }
    // Very important: Wait 1 second to respect Giphy Rate Limiting!
    await new Promise(r => setTimeout(r, 1000));
  }

  sqlStatements += values.join(',\n');
  sqlStatements += `\nON CONFLICT (word) DO NOTHING;\n`;

  // Save the result
  const outputPath = path.join(process.cwd(), 'scripts', 'seed_data.sql');
  fs.writeFileSync(outputPath, sqlStatements);
  
  console.log(`\n🎉 Done! Generated SQL for ${values.length} words.`);
  console.log(`File saved to: ${outputPath}`);
  console.log("Next step: Copy the contents of this file into the Supabase SQL Editor and hit RUN!");
};

runPipeline();
