-- Prevent browsers from poisoning the shared dictionary cache.
-- Existing rows are trusted only after a structural/provenance audit.

alter table public.global_dictionary enable row level security;
alter table public.global_dictionary
  add column if not exists verification_status text not null default 'legacy_unverified',
  add column if not exists verified_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'global_dictionary_verification_status_check'
      and conrelid = 'public.global_dictionary'::regclass
  ) then
    alter table public.global_dictionary
      add constraint global_dictionary_verification_status_check
      check (verification_status in ('legacy_unverified', 'legacy_structural', 'server_verified'));
  end if;
end $$;

do $$
declare policy_record record;
begin
  for policy_record in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'global_dictionary'
      and cmd in ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'ALL')
  loop
    execute format('drop policy if exists %I on public.global_dictionary', policy_record.policyname);
  end loop;
end $$;

revoke insert, update, delete on public.global_dictionary from anon, authenticated;
grant select on public.global_dictionary to anon, authenticated;

drop policy if exists "App can read verified dictionary entries" on public.global_dictionary;
create policy "App can read verified dictionary entries"
  on public.global_dictionary for select to anon, authenticated
  using (verification_status in ('legacy_structural', 'server_verified'));

-- Keep the well-formed rows generated by the app's known historical providers.
update public.global_dictionary
set verification_status = 'legacy_structural',
    verified_at = now()
where word ~ '^[a-z][a-z -]{0,63}$'
  and rich_data is not null
  and jsonb_typeof(rich_data) = 'object'
  and rich_data ->> '_provider' = any (array[
    'Groq', 'Gemini', 'Cerebras', 'Offline Curated', 'Groq (Mixtral 8x7B)',
    'Local Groq Fallback', 'Cerebras (gpt-oss-120b)', 'Local Groq Fallback (Repaired)'
  ])
  and length(coalesce(rich_data #>> '{englishExplanation,definition}', '')) between 1 and 160
  and rich_data ->> 'cefrLevel' = any (array['A1', 'A2', 'B1', 'B2', 'C1', 'C2'])
  and jsonb_typeof(rich_data -> 'scenes') = 'array'
  and jsonb_array_length(rich_data -> 'scenes') = 2;

update public.global_dictionary
set verification_status = 'legacy_unverified',
    verified_at = null
where verification_status <> 'legacy_structural';
